# Generated by Django 6.0.3 on 2026-03-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('en', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
                ('uz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=100, unique=True)),
                ('sender_card_number', models.CharField(max_length=16)),
                ('receiver_card_number', models.CharField(max_length=16)),
                ('sender_card_expiry', models.CharField(max_length=5)),
                ('sender_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('sending_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.IntegerField()),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('created', 'created'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='created', max_length=20)),
                ('try_count', models.IntegerField(default=0)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
